### ISSUE TITLE
Django cms - ImportError: No module named compat - plugin contact plus.

### ISSUE THREAD

**Issue by olgacattin** [arteria/cmsplugin-contact-plus#35]
Hello,
I have an error with deploy my web application in server. In local this web application work well. I use the plugin contact plus 1.2.6, django 1.8, django-cms 3.2.3 and python 2.7

My error is : 
$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cms/plugin_pool.py", line 32, in discover_plugins
    load('cms_plugins')
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 61, in load
    get_module(app, modname, verbose, failfast)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cms/utils/django_load.py", line 45, in get_module
    module = import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cmsplugin_contact_plus/cms_plugins.py", line 6, in <module>
    from cmsplugin_contact_plus.admin import ExtraFieldInline
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cmsplugin_contact_plus/admin.py", line 7, in <module>
    from .actions import export_as_csv_action
  File "/var/www/virtualenvs/bcis_site_cms_test/local/lib/python2.7/site-packages/cmsplugin_contact_plus/actions.py", line 3, in <module>
    from setuptools.compat import unicode
ImportError: No module named compat

My applications installation in my environ virtual are:

cmsplugin-contact-plus (1.2.6)
cmsplugin-filer (1.0.1)
codecov (1.6.3)
coverage (4.0.3)
distribute (0.6.24)
dj-database-url (0.4.0)
Django (1.8)
django-admin-jqueryui (1.8.22)
django-appconf (1.0.1)
django-classy-tags (0.7.2)
django-cms (3.2.3)
django-compat (1.0.10)
django-filer (1.1.1)
django-formtools (1.0)
django-inline-ordering (1.0.2)
django-mptt (0.8.3)
django-polymorphic (0.9.1)
django-recaptcha (1.0.5)
django-reversion (1.8.7)
django-sekizai (0.9.0)
Django-Select2 (4.3.2)
django-simple-math-captcha (1.0.7)
django-treebeard (4.0)
djangocms-admin-style (1.1.0)
djangocms-column (1.6.0)
djangocms-file (1.0)
djangocms-googlemap (0.4.0)
djangocms-inherit (0.1.1)
djangocms-installer (0.9rc2, /var/www/virtualenvs/bcis_site_cms_test/src/djangocms-installer)
djangocms-link (1.7.2)
djangocms-style (1.7.0)
djangocms-text-ckeditor (2.9.0)
easy-thumbnails (2.3)
html5lib (1.0b8)
jsonfield (1.0.3)
Pillow (3.1.1)
pip (8.1.1)
pytz (2016.3)
requests (2.9.1)
setuptools (20.3.1)
six (1.10.0)
tzlocal (1.2.2)
Unidecode (0.4.19)

and my requirements.txt file is : 
$ cat requirements.txt 
django-cms<3.3
django-treebeard>=2.0

https://github.com/divio/djangocms-column/archive/master.zip?1457965105.28
https://github.com/divio/djangocms-googlemap/archive/master.zip?1457965105.28
https://github.com/divio/djangocms-inherit/archive/master.zip?1457965105.28
https://github.com/divio/djangocms-link/archive/master.zip?1457965105.28
https://github.com/divio/djangocms-style/archive/master.zip?1457965105.28
easy_thumbnails
django-filer>=0.9.12
cmsplugin-filer>=0.10.2
djangocms-admin-style>=1.0.6
djangocms-text-ckeditor>=2.8.1
Django<1.9
pytz
django-reversion>=1.8.7,<1.9
django-classy-tags>=0.3.4.1
html5lib
Pillow>=2.3
django-sekizai>=0.7
six

Thank you for your help.

**Comment by jvamvas** [comment]
Thank you for reporting this bug, @olgacattin. It was caused by an outdated dependency on a setuptools submodule. We have removed the dependency and have released a new version (1.2.7).

Please report back if the deployment still causes an error.

**Comment by olgacattin** [comment]
It's works!, thanks you so much.
