### ISSUE TITLE
Python 2 Compatible?

### ISSUE THREAD

**Issue by lukyncze** [arteria/cmsplugin-contact-plus#71]
Hello, this happens when i install a plugin and make a migrations. Any ideas?

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\Final-project\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\Final-project\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Final-project\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\Final-project\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\lukas\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Final-project\env\lib\site-packages\cmsplugin_contact_plus\models.py", line 5, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (D:\Final-project\env\lib\site-packages\django\utils\encoding.py)

**Comment by debdolph** [comment]
Any progress?

**Comment by lukyncze** [comment]
I have not worked on it, so I do not know.
